---
- when: git_mirrors | length > 1
  block:
  - name: Ensure directories exist
    loop:
      - "{{ git_mirror_dir }}"
    file:
      state: directory
      path: "{{ item }}"


  - loop: "{{ git_mirrors }}"
    loop_control:
      loop_var: repo
    include_tasks: mirror.yml
