---
- when: git_mirrors | length > 1
  block:
  - name: Sort & distinct the repo list
    set_fact:
      git_mirrors: "{{ git_mirrors | sort | unique }}"

  - name: List the git repositories being mirrored
    debug:
      var: git_mirrors

  - name: Ensure directories exist
    loop: ["{{ git_mirror_dir }}"]
    file:
      state: directory
      path: "{{ item }}"


  - loop: "{{ git_mirrors }}"
    loop_control:
      loop_var: repo
      index_var: index
    vars:
      total: "{{ git_mirrors | length }}"
    include_tasks: mirror.yml
