---
- name: "Set mirror name"
  set_fact:
    mirror_name: "{{ repo | urlsplit('path') | replace('/', '', 1) | replace('/', '-') }}"

- name: "Set mirror dir"
  set_fact:
    mirror_dir: "{{ git_mirror_dir }}/{{ mirror_name }}"

- name: Check if repo exists
  register: dir
  stat:
    path: "{{ git_mirror_dir }}/{{ mirror_name }}"

- when: not dir.stat.exists
  block:
    - debug:
        msg: "Cloning {{ repo }} -> {{ mirror_name }}..."

    - name: Clone repository
      command: git clone "{{ repo }}" "{{ mirror_dir }}"

- when: dir.stat.exists
  block:
    - debug:
        msg: "Updating {{ mirror_name }}..."

    - name: Update repository
      command: git remote update
      args:
        chdir: "{{ mirror_dir }}"

