---
- set_fact:
    mirror_name: "{{ repo | urlsplit('path') | replace('/', '', 1) | replace('/', '-') }}"


- name: Check if repo exists
  stat:
    path: "{{ git_mirror_clone_dir }}/{{ mirror_name }}"
  register: repo_dir

- when: not repo_dir.stat.exists
  block:
    - debug:
        msg: "Cloning {{ repo }} into {{ mirror_name }}..."

    - name: Clone repository
      command: git clone "{{ repo }}" "{{ mirror_name }}"
      args:
        chdir: "{{ git_mirror_clone_dir }}"
- when: repo_dir.stat.exists
  block:
    - debug:
        msg: "Updating {{ mirror_name }}..."

    - name: Update repository
      command: git remote update
      args:
        chdir: "{{ git_mirror_clone_dir }}/{{ mirror_name }}"

