---
- set_fact:
    repos_all: "{{
      lookup('filetree', git_mirror_dir)
        | selectattr('path', 'match', '^.*[^\\/]\\.git$')
        | selectattr('state', 'eq', 'directory')
        | map(attribute='path')
        | list
      }}"
      custom_repo_map: "{{ git_mirrors | repo_map(git_mirror_default_dest) }}"
      dir_repo_map: "{{ repos_all | repo_map(git_mirror_default_dest) }}"

- set_fact:
    repos_default_dest: "{{ all_repos | difference(custom_repos) }}"

- debug: var=all_repos
- debug: var=repos_default_dest
- debug: var=repos_custom_dest
