---
- set_fact:
    all_repos: "{{
      lookup('filetree', git_mirror_dir)
        | selectattr('path', 'match', '^.*[^\\/]\\.git$')
        | selectattr('state', 'equals', 'directory')
        | map(attribute='path')
        | list
      }}"
    dest_custom: "{{ git_mirrors | map(attribute='src') | list }}"

- set_fact:
    dest_default: "{{ all_repos | difference(custom_repos) }}"

- debug: var=all_repos
- debug: var=custom_repos
- debug: var=default_repos
