---
- set_fact:
    all_repos: "{{
      lookup('filetree', git_mirror_dir)
        | selectattr('path', 'match', '^.*[^\\/]\\.git$')
        | selectattr('state', 'eq', 'directory')
        | map(attribute='path')
        | list
      }}"
    repos_custom_dest: "{{ git_mirrors | map(attribute='src') | list }}"

- set_fact:
    repos_default_dest: "{{ all_repos | difference(custom_repos) }}"

- debug: var=all_repos
- debug: var=repos_default_dest
- debug: var=repos_custom_dest
